// AUTO-GENERATED: mixed int/float delegate matrix up to N=4
using System.Threading.Tasks;
using System;
using System.Runtime.InteropServices;

namespace RaLanguage.Interpreter.Runtime.Interop
{
    public static class MixedDelegates
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate void V_FFFF(double a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate IntPtr P_FFFF(double a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate int I32_FFFF(double a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate long I64_FFFF(double a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate float F32_FFFF(double a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_0();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_I(IntPtr a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_F(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_II(IntPtr a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IF(IntPtr a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FI(double a0, IntPtr a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FF(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_III(IntPtr a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IIF(IntPtr a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFI(IntPtr a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFF(IntPtr a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FII(double a0, IntPtr a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FIF(double a0, IntPtr a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFI(double a0, double a1, IntPtr a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFF(double a0, double a1, double a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IIII(IntPtr a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IIIF(IntPtr a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IIFI(IntPtr a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IIFF(IntPtr a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFII(IntPtr a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFIF(IntPtr a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFFI(IntPtr a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_IFFF(IntPtr a0, double a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FIII(double a0, IntPtr a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FIIF(double a0, IntPtr a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FIFI(double a0, IntPtr a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FIFF(double a0, IntPtr a1, double a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFII(double a0, double a1, IntPtr a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFIF(double a0, double a1, IntPtr a2, double a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFFI(double a0, double a1, double a2, IntPtr a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] public delegate double F64_FFFF(double a0, double a1, double a2, double a3);
    }
}
